[package]
name = "gbspack"
version = "1.2.2"
authors = ["Chris Maltby <chris.maltby@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"