version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/rust:1.49.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-gbspack-src-{{ .Branch }}-{{ .Revision }}
            - v1-gbspack-src-{{ .Branch }}-
            - v1-gbspack-src-
      - checkout
      - save_cache:
          paths:
            - ./*
          key: v1-gbspack-src-{{ .Branch }}-{{ .Revision }}
      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  test:
    docker:
      - image: circleci/rust:1.49.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: cargo test

workflows:
  version: 2
  deployment:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
